namespace: dddsample

resources:
- sqlserver
- mongodb
- redis
- kafka
- catalog-api
- ordering-api
- payment-api
- identity-api
- namespace.yaml
- dashboard.yaml

generatorOptions:
  disableNameSuffixHash: true


