resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: sqlserver-env
  literals:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=051093@Galvin
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=sqlserver

