resources:
- statefulset.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: mongodb-env
  literals:
    - MONGO_INITDB_ROOT_USERNAME=jWKuHUia!4mySUV2ZZw8V7
    - MONGO_INITDB_ROOT_PASSWORD=ChangeMe_MongoPassword!
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=mongodb

