---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  labels:
    app: catalog-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: ghcr.io/dddsample/catalog-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5100
        envFrom:
        - configMapRef:
            name: catalog-api-env
      terminationGracePeriodSeconds: 180