resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: catalog-api-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=5100
    - ASPNETCORE_ENVIRONMENT=Development
    - DOTNET_ENVIRONMENT=Development
    - ASPNETCORE_PREVENTHOSTINGSTARTUP=true
    - Hosting__Restful__Http=5100
    - Kafka__BootstrapServers=kafka:9092
    - ConnectionStrings__Default=Server=sqlserver,1433;User ID=sa;Password=051093@Galvin;TrustServerCertificate=true;Initial Catalog=CatalogAPI
    - DEFAULT_HOST=sqlserver
    - DEFAULT_PORT=1433
    - DEFAULT_USERNAME=sa
    - DEFAULT_PASSWORD=051093@Galvin
    - DEFAULT_URI=mssql://sa:051093@Galvin@sqlserver:1433/CatalogAPI
    - DEFAULT_JDBCCONNECTIONSTRING=jdbc:sqlserver://sqlserver:1433;databaseName=CatalogAPI;trustServerCertificate=true
    - DEFAULT_DATABASENAME=CatalogAPI
    - ConnectionStrings__Redis=redis:6379,password=u20JztpEwmw!1ViqtbrKNs
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=u20JztpEwmw!1ViqtbrKNs
    - REDIS_URI=http://:{redis-password-uri-encoded.value}@redis:6379
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=catalog-api
    - ASPNETCORE_URLS=http://+:8080;

