resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: identity-api-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=5108
    - ASPNETCORE_ENVIRONMENT=Development
    - DOTNET_ENVIRONMENT=Development
    - ASPNETCORE_PREVENTHOSTINGSTARTUP=true
    - Hosting__Restful__Http=5108
    - ConnectionStrings__MongoDB=mongodb://{mongodb-username-uri-encoded.value}:{mongodb-password-uri-encoded.value}@mongodb:27017/identitydb?authSource=admin&amp;authMechanism=SCRAM-SHA-256
    - MONGODB_HOST=mongodb
    - MONGODB_PORT=27017
    - MONGODB_USERNAME=q!aGCgQlvS1yFvB1WCBiFB
    - MONGODB_PASSWORD=identity_password
    - MONGODB_AUTHENTICATIONDATABASE=admin
    - MONGODB_AUTHENTICATIONMECHANISM=SCRAM-SHA-256
    - MONGODB_URI=mongodb://{mongodb-username-uri-encoded.value}:{mongodb-password-uri-encoded.value}@mongodb:27017/identitydb?authSource=admin&amp;authMechanism=SCRAM-SHA-256
    - MONGODB_DATABASENAME=identitydb
    - ConnectionStrings__Redis=redis:6379,password=u20JztpEwmw!1ViqtbrKNs
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=u20JztpEwmw!1ViqtbrKNs
    - REDIS_URI=http://:{redis-password-uri-encoded.value}@redis:6379
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=identity-api
    - ASPNETCORE_URLS=http://+:8080;

